### ISSUE TITLE
Missing /usr/share/doc/packages/rpm/manual/spec.md

### ISSUE THREAD

**Issue by mcepl** [dcermak/rpm-spec-language-server#30]
On [MicroOS-based system](https://build.opensuse.org/project/show/home:mcepl:moldavite) with `rpm.excludeDocs = True`:
```
tumbleweed-pkg/tmp$ python3 -mrpm_spec_language_server --stdio
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/matej/archiv/2023/projekty/rpm_spec_lsp_server/rpm_spec_language_server/__main__.py", line 4, in <module>
    main()
  File "/home/matej/archiv/2023/projekty/rpm_spec_lsp_server/rpm_spec_language_server/main.py", line 35, in main
    server = create_rpm_lang_server()
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/matej/archiv/2023/projekty/rpm_spec_lsp_server/rpm_spec_language_server/server.py", line 47, in create_rpm_lang_server
    spec_md_from_rpm_db() or ""
    ^^^^^^^^^^^^^^^^^^^^^
  File "/home/matej/archiv/2023/projekty/rpm_spec_lsp_server/rpm_spec_language_server/extract_docs.py", line 154, in spec_md_from_rpm_db
    with open(path) as spec_md_f:
         ^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/usr/share/doc/packages/rpm/manual/spec.md'
tumbleweed-pkg/tmp$ 
```

**Comment by mcepl** [comment]
Fixed in https://github.com/dcermak/rpm-spec-language-server/commit/9a4e8fb1103e0b41b39d775c65b11a473ed9fd61.
